# To run all pre-commit checks, use:
#
#     pre-commit run -a
#
# To install pre-commit hooks that run every time you commit:
#
#     pre-commit install
#

ci:
  autoupdate_commit_msg: "⬆️🪝 update pre-commit hooks"
  autofix_commit_msg: "🎨 pre-commit fixes"

repos:
  # Standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  # Clean jupyter notebooks
  - repo: https://github.com/srstevenson/nb-clean
    rev: "4.0.1"
    hooks:
      - id: nb-clean

  # Check for common mistakes
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal

  # Handling unwanted unicode characters
  - repo: https://github.com/sirosen/texthooks
    rev: 0.6.7
    hooks:
      - id: fix-ligatures
      - id: fix-smartquotes

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.0
    hooks:
      - id: ruff
        args: ["--fix"]

  # Run code formatting with Black
  - repo: https://github.com/psf/black
    rev: 24.10.0 # Keep in sync with blacken-docs
    hooks:
      - id: black-jupyter

  # Also run Black on examples in the documentation
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.19.0
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black==23.3.0 # keep in sync with black hook

  # Format configuration files with prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        types_or: [yaml, markdown, html, css, scss, javascript, json]

  # Check for spelling
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args: ["-L", "wille,linz,braket,coo", "--skip", "*.ipynb"]
